fix set/get client; add currency to request/response
hiqdev/omnipay-freekassa pull request #2
Opened 2021-03-02 12:43 UTC by bladeroot

2021-03-29 15:00 UTC, hiqsol requested changes

2021-03-29 15:00 UTC, hiqsol commented on src/Message/PurchaseRequest.php
> +    public function getClient() : string
```suggestion
    public function getClient(): string
```

2021-03-29 15:40 UTC, SilverFire requested changes

2021-03-29 15:40 UTC, SilverFire commented on src/Message/PurchaseRequest.php
> +    public function setCurrency($value)
Этот метод уже есть в `Omnipay\Common\Message\AbstractRequest` и отличается только отсутствием `uppercase`a.

Он точно тут нужен?

2021-03-29 15:40 UTC, SilverFire commented on src/Message/PurchaseRequest.php
> +        return $this->getParameter('currency') ?? 'RUB';
```suggestion
        return parent::getCurrency() ?: 'RUB';
```

2021-03-29 16:05 UTC, bladeroot commented on src/Message/PurchaseRequest.php
> +        return $this->getParameter('currency') ?? 'RUB';
Нужен. Call to undefined method Omnipay\\FreeKassa\\Message\\CompletePurchaseResponse::getCurrency()

2021-03-29 16:07 UTC, bladeroot commented on src/Message/PurchaseRequest.php
> +        return $this->getParameter('currency') ?? 'RUB';
Тьфу, не то. Но таки нужен. Ибо валюта кошелька может быть другой. И по дефолту фрикасса принимает рубли =(

2021-03-30 06:36 UTC, SilverFire commented on src/Message/PurchaseRequest.php
> +    public function setCurrency($value)
А тут?

2021-04-02 07:20 UTC, hiqsol commented
Done in #3

2021-04-02 07:20 UTC, closed without merging