Add currency
hiqdev/omnipay-freekassa pull request #3
Opened 2021-04-02 07:09 UTC by bladeroot

2021-04-02 07:19 UTC, hiqsol approved these changes

2021-04-02 10:40 UTC, strorch requested changes

2021-04-02 10:40 UTC, strorch commented on src/Message/CompletePurchaseResponse.php
> +        return $this->data['us_currency'] ?? 'RUB';
це костиль який то хоча б параметр завети тіпа self::DEFAULT_CURRENCY

2021-04-02 10:40 UTC, strorch commented on src/Message/PurchaseRequest.php
> +            'us_currency' => strtoupper($this->getCurrency() ?? 'RUB'),
ще й тут повторюється

2021-04-02 10:45 UTC, bladeroot commented on src/Message/CompletePurchaseResponse.php
> +        return $this->data['us_currency'] ?? 'RUB';
І все одно буде костиль, так як воно в двох різних класах.

2021-04-05 09:29 UTC, strorch commented on src/Message/CompletePurchaseResponse.php
> +        return $this->data['us_currency'] ?? 'RUB';
можна завести трейт з константой і додать його у 2 класа

2021-04-05 13:11 UTC, merged